// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DishProduct", b =>
                {
                    b.Property<int>("DishesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("DishesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("DishProduct");

                    b.HasData(
                        new
                        {
                            DishesId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            DishesId = 2,
                            ProductsId = 2
                        },
                        new
                        {
                            DishesId = 2,
                            ProductsId = 1
                        },
                        new
                        {
                            DishesId = 3,
                            ProductsId = 1
                        },
                        new
                        {
                            DishesId = 3,
                            ProductsId = 2
                        },
                        new
                        {
                            DishesId = 3,
                            ProductsId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Base.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Some dish 0",
                            Name = "Sombrero",
                            PictureUrl = "images/dishes/Dish1.png",
                            Price = 20.50m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Some dish 1",
                            Name = "Mustangi",
                            PictureUrl = "images/dishes/Dish2.jpg",
                            Price = 73.0m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "Some dish 2",
                            Name = "Eleonore",
                            PictureUrl = "images/dishes/Dish3.jpg",
                            Price = 2.0m,
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Base.DishType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("DishTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Soup"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Desert"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cold Snap"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hot Snap"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Special"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Base.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fish",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Milk",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beef",
                            TypeId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Base.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Meat"
                        });
                });

            modelBuilder.Entity("DishProduct", b =>
                {
                    b.HasOne("Domain.Entities.Base.Dish", null)
                        .WithMany()
                        .HasForeignKey("DishesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Base.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Base.Dish", b =>
                {
                    b.HasOne("Domain.Entities.Base.DishType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Entities.Base.Product", b =>
                {
                    b.HasOne("Domain.Entities.Base.ProductType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
